export const peopleData =
[{
    "id": 1,
    "avatar": "https://robohash.org/atqueetconsequatur.png?size=50x50&set=set1",
    "first_name": "Maury",
    "last_name": "Hurst",
    "email": "mhurst0@netlog.com",
    "gender": "Male"
  }, {
    "id": 2,
    "avatar": "https://robohash.org/quomollitialaudantium.png?size=50x50&set=set1",
    "first_name": "Bryn",
    "last_name": "De Lasci",
    "email": "bdelasci1@ifeng.com",
    "gender": "Male"
  }, {
    "id": 3,
    "avatar": "https://robohash.org/doloremassumendavoluptatem.png?size=50x50&set=set1",
    "first_name": "Rickert",
    "last_name": "Sanzio",
    "email": "rsanzio2@flickr.com",
    "gender": "Male"
  }, {
    "id": 4,
    "avatar": "https://robohash.org/minusofficiisconsectetur.png?size=50x50&set=set1",
    "first_name": "Lurleen",
    "last_name": "Eglaise",
    "email": "leglaise3@mac.com",
    "gender": "Female"
  }, {
    "id": 5,
    "avatar": "https://robohash.org/deseruntsitarchitecto.png?size=50x50&set=set1",
    "first_name": "Farica",
    "last_name": "Cloonan",
    "email": "fcloonan4@webeden.co.uk",
    "gender": "Non-binary"
  }, {
    "id": 6,
    "avatar": "https://robohash.org/quiipsamquasi.png?size=50x50&set=set1",
    "first_name": "Jackqueline",
    "last_name": "Alanbrooke",
    "email": "jalanbrooke5@cpanel.net",
    "gender": "Female"
  }, {
    "id": 7,
    "avatar": "https://robohash.org/voluptatemveritatisvoluptatibus.png?size=50x50&set=set1",
    "first_name": "Christyna",
    "last_name": "Lorriman",
    "email": "clorriman6@addtoany.com",
    "gender": "Genderqueer"
  }, {
    "id": 8,
    "avatar": "https://robohash.org/voluptatumofficiisnihil.png?size=50x50&set=set1",
    "first_name": "Elston",
    "last_name": "Arboin",
    "email": "earboin7@springer.com",
    "gender": "Male"
  }, {
    "id": 9,
    "avatar": "https://robohash.org/utessecommodi.png?size=50x50&set=set1",
    "first_name": "Gillie",
    "last_name": "Winny",
    "email": "gwinny8@networkadvertising.org",
    "gender": "Female"
  }, {
    "id": 10,
    "avatar": "https://robohash.org/doloribusabnobis.png?size=50x50&set=set1",
    "first_name": "Elena",
    "last_name": "Haylor",
    "email": "ehaylor9@uiuc.edu",
    "gender": "Female"
  }]